const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    picture: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',
    fullness: 67,
    favoritePose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat2',
    name: 'tommy',
    disposition: 'rude',
    picture: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Hausziege_04.jpg/220px-Hausziege_04.jpg',
    fullness: 50,
    favoritePose: 'downward facing whale',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat3',
    name: 'jim',
    disposition: 'kind',
    picture: 'https://images2.minutemediacdn.com/image/upload/c_crop,h_843,w_1500,x_0,y_0/f_auto,q_auto,w_1100/v1555172619/shape/mentalfloss/iStock-177369626_0.jpg',
    fullness: 100,
    favoritePose: 'downward facing squirrel',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name: 'carl',
    disposition: 'angry',
    picture: 'https://thumbs-prod.si-cdn.com/X1ZibsBP5j3g6ccUN31rYco4_YM=/fit-in/1600x0/https://public-media.si-cdn.com/filer/b9/d2/b9d271f3-7f66-4132-b5af-7d33844505b7/goat.jpg',
    fullness: 11,
    favoritePose: 'downward facing turtle',
    isFainting: false,
    color: 'white',
  },
  {
    id: 'goat5',
    name: 'dan',
    disposition: 'friendly',
    picture: 'https://images.theconversation.com/files/129851/original/image-20160708-24096-1mslcn7.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=926&fit=clip',
    fullness: 88,
    favoritePose: 'downward facing rabbit',
    isFainting: false,
    color: 'black',
  },
];

export default goats;
